name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Cake.Console.sln
    - name: Build
      run: dotnet build src/Cake.Console.sln --no-restore
    - name: Test
      run: scripts/test.ps1
    - name: Pack
      run: dotnet pack src/Cake.Console/Cake.Console.csproj -c=Release
    - name: Publish
      run: dotnet nuget push src/Cake.Console/bin/Release/net5.0/*.nupkg -k ${NUGET_API_KEY} --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
