name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack src/Cake.Console/Cake.Console.csproj -c=Release
    - name: Publish
      run: dotnet nuget push src/Cake.Console/bin/Release/Cake.Console.*.nupkg --source $env:PUSH_SOURCE --api-key $env:NUGET_API_KEY --skip-duplicate
      env:
        PUSH_SOURCE: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
